import { Prompt, League_Spartan } from "next/font/google";
import "@/style/globals.css";

const prompt = Prompt({
  subsets: ["latin"],
  variable: "--prompt",
  weight: "300",
  display: "swap",
});

const league_Spartan = League_Spartan({
  subsets: ["latin"],
  variable: "--league_Spartan",
  weight: "300",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${league_Spartan.variable} ${prompt.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
