import { Prompt, League_Spartan } from "next/font/google";
import "@/style/globals.css";
import {
  Chat,
  Layers,
  Phone,
  Map,
  En,
  Th,
  Star,
} from "@/components/icons/icons";

const prompt = Prompt({
  subsets: ["latin"],
  variable: "--prompt",
  weight: "300",
  display: "swap",
});

const league_Spartan = League_Spartan({
  subsets: ["latin"],
  variable: "--league_Spartan",
  weight: "300",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${league_Spartan.variable} ${prompt.variable} antialiased`}
      >
        <div className="flex flex-col items-center justify-start w-full min-h-screen py-2 gap-2">
          <div className="flex flex-row items-center justify-center w-full h-16 px-10 py-2 gap-2">
            <div className="flex items-center justify-between w-full h-full p-2 gap-2 border-2 border-default bg-default rounded-xl">
              <span className="font-[600]">Channakorn</span>
              <span className="text-[#555555]">Office For Rent</span>
            </div>
            <div className="flex items-center justify-center h-full px-6 py-2 gap-2 border-2 border-secondary rounded-xl">
              <Phone />
            </div>
            <div className="flex items-center justify-center h-full px-6 py-2 gap-2 border-2 border-secondary rounded-xl">
              <Chat />
            </div>
            <div className="flex items-center justify-center h-full px-6 py-2 gap-2 border-2 border-secondary rounded-xl">
              <Map />
            </div>
            <div className="flex items-center justify-between w-full h-full p-2 gap-2 border-2 border-default bg-default rounded-xl">
              <span>Menu</span>
              <span>
                <Star />
              </span>
            </div>
            <div className="flex items-center justify-center h-full px-6 py-2 gap-2 border-2 border-secondary rounded-xl">
              <En /> <Th />
            </div>
            <div className="flex items-center justify-center h-full px-6 py-2 gap-2 border-2 border-default bg-default rounded-xl">
              <span>CONTACT</span>
              <span>US</span>
            </div>
            <div className="lg:hidden flex items-center justify-center h-full px-6 py-2 gap-2 border-2 border-secondary rounded-xl">
              <Layers />
            </div>
          </div>
          <div className="flex flex-row items-center justify-center w-full h-full p-2 gap-2 border-2 border-dark border-dashed">
            1
          </div>
        </div>
      </body>
    </html>
  );
}
