import { Prompt, League_Spartan } from "next/font/google";
import "@/style/globals.css";
import { Chat, Layers, Phone, Map, Star } from "@/components/icons/icons";
import { NextIntlClientProvider } from "next-intl";
import { getLocale } from "next-intl/server";
import LanguageSwitcher from "@/components/other/LanguageSwitcher";

const prompt = Prompt({
  subsets: ["latin"],
  variable: "--prompt",
  weight: "300",
  display: "swap",
});
const leagueSpartan = League_Spartan({
  subsets: ["latin"],
  variable: "--league_Spartan",
  weight: "300",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return [{ locale: "en" }, { locale: "th" }];
}

export default async function RootLayout({ children }) {
  const locale = await getLocale();

  return (
    <html lang={locale}>
      <body
        className={`${leagueSpartan.variable} ${prompt.variable} antialiased`}
      >
        <NextIntlClientProvider>
          <div className="flex flex-col items-center justify-start w-full min-h-screen py-2 gap-2">
            <div className="flex flex-row items-center justify-center w-full h-16 px-10 py-2 gap-2">
              <div className="flex items-center justify-between w-full h-full p-2 gap-2 border-2 border-default bg-default rounded-xl">
                <span className="font-[600]">Channakorn</span>
                <span className="text-[#555555]">
                  Office&nbsp;For&nbsp;Rent
                </span>
              </div>

              <div className="flex items-center justify-center h-full px-6 py-2 gap-2 border-2 border-secondary rounded-xl">
                <Phone />
              </div>
              <div className="flex items-center justify-center h-full px-6 py-2 gap-2 border-2 border-secondary rounded-xl">
                <Chat />
              </div>
              <div className="flex items-center justify-center h-full px-6 py-2 gap-2 border-2 border-secondary rounded-xl">
                <Map />
              </div>
              <div className="flex items-center justify-between w-full h-full p-2 gap-2 border-2 border-default bg-default rounded-xl">
                <span>Menu</span>
                <Star />
              </div>
              <div className="flex items-center justify-center h-full px-6 py-2 gap-2 border-2 border-secondary rounded-xl">
                <LanguageSwitcher />
              </div>
              <div className="flex items-center justify-center h-full px-6 py-2 gap-2 border-2 border-default bg-default rounded-xl">
                <span className="font-[600]">Contact&nbsp;Us</span>
              </div>
              <div className="lg:hidden flex items-center justify-center h-full px-6 py-2 gap-2 border-2 border-secondary rounded-xl">
                <Layers />
              </div>
            </div>
            <div className="flex items-center justify-center w-full h-full gap-2">
              {children}
            </div>
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
