// app/[locale]/layout.jsx
import { Mitr, Teko } from "next/font/google";
import "@/style/globals.css";
import { Chat, Phone, Map, Star } from "@/components/icons/icons";
import LanguageSwitcher from "@/components/other/LanguageSwitcher";
import MobileMenu from "@/components/other/MobileMenu";
import { NextIntlClientProvider } from "next-intl";
import { getLocale } from "next-intl/server";
import Link from "next/link";

const mitr = Mitr({
  subsets: ["latin"],
  variable: "--mitr",
  weight: "300",
  display: "swap",
});
const leagueSpartan = Teko({
  subsets: ["latin"],
  variable: "--teko",
  weight: "300",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return [{ locale: "en" }, { locale: "th" }];
}

export default async function RootLayout({ children }) {
  const locale = await getLocale();

  return (
    <body
      className={`${leagueSpartan.variable} ${mitr.variable} antialiased`}
    >
      <NextIntlClientProvider>
        <div className="flex flex-col items-center justify-start w-full min-h-screen py-2 gap-2">
          <div className="flex flex-row items-center justify-center w-full h-16 px-2 lg:px-10 py-2 gap-2">
            <div className="flex items-center justify-between w-full h-full p-2 gap-2 border-2 border-default bg-default rounded-xl">
              <span className="font-[600]">Channakorn</span>
              <span className="text-[#555555]">Office&nbsp;For&nbsp;Rent</span>
            </div>
            <Link
              href="tel:0909075310"
              title="โทร 090-907-5310"
              className="hidden lg:flex items-center justify-center h-full px-6 py-2 gap-2 border-2 border-secondary rounded-xl"
            >
              <Phone />
            </Link>
            <Link
              href="https://line.me/ti/p/buwWdN4vVx"
              target="_blank"
              className="hidden lg:flex items-center justify-center h-full px-6 py-2 gap-2 border-2 border-secondary rounded-xl"
            >
              <Chat />
            </Link>
            <Link
              href="https://www.google.com/maps/dir//50,+ซอย+งามวงศ์วาน+57..."
              target="_blank"
              className="hidden lg:flex items-center justify-center h-full px-6 py-2 gap-2 border-2 border-secondary rounded-xl"
            >
              <Map />
            </Link>
            <div className="hidden lg:flex items-center justify-between w-full h-full p-2 gap-2 border-2 border-default bg-default rounded-xl">
              <span>{""}</span>
              <Star />
            </div>
            <div className="hidden lg:flex items-center justify-center h-full px-6 py-2 gap-2 border-2 border-secondary rounded-xl">
              <LanguageSwitcher />
            </div>
            <Link
              href="tel:0909075310"
              title="โทร 090-907-5310"
              className="hidden lg:flex items-center justify-center h-full px-6 py-2 gap-2 border-2 border-default bg-default rounded-xl"
            >
              <span className="font-[600]">Contact&nbsp;Us</span>
            </Link>
            <MobileMenu />
          </div>
          <div className="flex items-center justify-center w-full h-full gap-2">
            {children}
          </div>
        </div>
      </NextIntlClientProvider>
    </body>
  );
}
